### PR TITLE
Blocks update for 1.15

### PR DESCRIPTION
**Pull request by miclav**
This pull request contains:
- The blocks updated for the 1.15 update (honey, beehives, chests fixes)
- The bamboo jungle biomes declaration
- Support for cave biome data format by @bemk https://github.com/mapcrafter/mapcrafter/pull/347/commits/2a35cf5779544c647331f3bc74cb7cb1a1332a93
Related to: #346

Screen Shot 2020-01-09 at 16 29 22
Screen Shot 2020-01-09 at 16 29 33

### CODE REVIEW

**Comment by elamperti** [comment]
I was able to build and render a 1.15 map successfuly (although there are lots of warnings for outdated biomes?)

    [WARNING] [default] Out dated chunk -11:-103: Old biome data found!

Other than that, it's looking good.

Selection_105

I'll test with a 1.14 map we're using in a server to see if anything else breaks, but so far it looks good :+1: Great work!

**Comment by miclav** [comment]
Bells are now also rendered correctly
image

**Comment by ddoiron79** [comment]
my error the map was generated in 12*12 resolution and it need to be 16*16 to fit with marker

**Comment by elamperti** [comment]
@ddoiron79 although not related with the changes on this PR, if the markers are wrongly positioned with different resolutions then it's a bug and it should have [its own issue](https://github.com/mapcrafter/mapcrafter/issues/new).

**Comment by jasonwc** [comment]
Also can verify this works! Deployed alongside a minecraft server using the [Docker image](https://hub.docker.com/r/dinip/mapcrafter) and it works great! Saw the same warnings, but the rendered map looks fine.

**Comment by matthewpayne** [comment]
Any chance someone can compile this for Windows.  I can't seem to compile it, or don't know how for windows.  I really need to map out 1.15.  I really wish this was merged.. thanks for the good work

**Comment by cliffmeyers** [comment]
@matthewpayne not sure if this helps, but if you're on W10 you can install Ubuntu via Windows Subsystem for Linux and follow the Linux instructions. It's worked well for me.

**Review by elamperti — APPROVED** [review]
Assuming @bemk changes in chunk format are ok, this PR is looking good to be merged into `world113`. Thanks for your contribution @miclav!

**Comment by m0r13** [comment]
Just had a look as well. Code looks good, I'm just wondering with the slight change in the world biome format if it's possible/useful to support the biome format 1.14 as well.

**Comment by Ghost-chu** [comment]
Can i have a build for this pr?
I'm glad to test and reporting if there have any bugs ^ ^

**Comment by m0r13** [comment]
@Ghost-chu unfortunately the build system is not ready for that at the moment. Hopefully in the future.

**Comment by elamperti** [comment]
@m0r13 I've just opened #351 to track the 1.14 biome format, so we can greenlight this PR, merge it and keep `world113` as reference for the 1.13+ changes.

Is there anything else pending to merge this?

**Comment by m0r13** [comment]
Think good to go then.

**Comment by josephrooks** [comment]
> I was able to build and render a 1.15 map successfuly (although there are lots of warnings for outdated biomes?)
> 
> ```
> [WARNING] [default] Out dated chunk -11:-103: Old biome data found!
> ```
> 
> Other than that, it's looking good.
> 
> Selection_105
> 
> I'll test with a 1.14 map we're using in a server to see if anything else breaks, but so far it looks good 👍 Great work!

The game updates chunk data as new chunks are loaded, does that map have chunks on it you generated in a previous version and haven't visited again in a newer one? You can force it to update  the whole map to the latest version by starting the server up with the -forceupgrade flag. It'll load each chunk, update it, and save it.

This warning might just be to let you know it's rendering chunks that are still using the old format, if you're not seeing anything visually wrong with them. I wouldn't know, but given that the format does change at least slightly with each version, it's probably a backwards compatibility thing that you can safely ignore.

**Comment by bemk** [comment]
@josephrooks The outdated chunks warning is because those chunks were generated using an older version of Minecraft, and the game only brings the biome data up to date when the chunk gets loaded anew.

The trick to avoid this, and I've described that in my pull request which has been merged into this one, is to start the server with a --forceUpgrade parameter on the command line. That way the server runs through all the chunks before opening up to clients.

If it weren't for a couple of mental health problems, I'd also have added dual support for the old and new formats. The difference between the two can be found by looking at the array size in the NBT data.

Another thing that's still missing, is that the biome data now also includes an elevation component. So a map maker would be able to stack multiple biomes on top of one another, but currently the biome data of the lowest 4x4x4 sub chunk is used by mapcrafter for the entire 4x4 column all the way up to build height. Again, I would have considered adding it if I didn't have a lack of focus at the minute.

**Comment by cliffmeyers** [comment]
Seems like updating the warning message `Old biome data found!` to include "did you use --forceUpgrade?" might be enough to steer people in the right direction on their own in the future?

**Comment by elamperti** [comment]
I'll be merging this branch so we can focus our efforts on `world113` and merge that one into master soon (after doing some checks and updating the README, at least!)

FYI @m0r13

**Comment by oskarkk** [comment]
Why there are no files with resolution lower than 12x12? Low resolutions would be good for some light, minimalist maps like from [Unmined](https://unmined.intro.hu/example/1.8.1_0.9.324/).

**Comment by slothbear** [comment]
Is ok to update an existing map (made from the master branch) with the world113 branch program? Or best to generate a new map from scratch? I am mapping a very large world and the full (non-update) method takes many hours.

**Comment by bemk** [comment]
@slothbear I haven't tested it, but from what I can tell if you update mapcrafter at the same time with the server executable, and run start that server executable at least once with the --force-upgrade option, it should mostly work with the existing images.

The way biomes are stored is changed a little, so you may find the biome edges may be up to 4 blocks off between the existing tiles sitting beside the newly updated tiles.

There may be a couple of other little glitches but nothing too bad really. And if all else fails, just let it crank for a couple of hours. It's what I did, but then again, the biome colours were all off before we updated that code.

**Pull request merged**
