### PR TITLE
1.16.1 block updated 

### PR DESCRIPTION
**Pull request by miclav**
Hi
This pull request is only an update to addd the latest of blocks from the Nether update.
However it doesn't handle the format changes in the chunk files.
To make the PR smaller it can be squashed as only the last commit is now relevant.

### CODE REVIEW

**Comment by miclav** [comment]
That should be it for the 1.16.1 to be functional.
I'm still battle testing it right now to check for edge cases, but so far it seems to do the trick.
Don't forget the latest of the blocstates update as walls got more complex in 1.16 and some properties were missing.

**Comment by fredkilbourn** [comment]
@miclav I'm not sure where to post this across mapcrafter/blockcrafter and your or their repos.  I ran my map with your latest world116 and blocks i built with your latest blockcrafter and I'm getting the following errors:
```
[INFO] [default] Unknown block minecraft:blackstone_wall east=low,north=none,south=none,up=false,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:blackstone_wall east=low,north=none,south=none,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:blackstone_wall east=low,north=none,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:blackstone_wall east=low,north=none,south=none,up=true,waterlogged=false,west=tall,
[INFO] [default] Unknown block minecraft:blackstone_wall east=none,north=none,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:blackstone_wall east=none,north=none,south=none,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:blackstone_wall east=none,north=none,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:blackstone_wall east=none,north=none,south=none,up=true,waterlogged=false,west=tall,
[INFO] [default] Unknown block minecraft:blackstone_wall east=tall,north=none,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:cobblestone_wall east=low,north=low,south=n
[INFO] [default] Unknown block minecraft:cobblestone_wall east=low,north=low,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:cobblestone_wall east=low,north=none,south=
[INFO] [default] Unknown block minecraft:cobblestone_wall east=low,north=none,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:cobblestone_wall east=none,north=low,south=
[INFO] [default] Unknown block minecraft:cobblestone_wall east=none,north=low,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:cobblestone_wall east=none,north=none,south
[INFO] [default] Unknown block minecraft:cobblestone_wall east=none,north=none,south=low,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:cobblestone_wall east=none,north=none,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:cobblestone_wall east=none,north=none,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:cobblestone_wall east=none,north=none,south=tall,up=true,waterlogged=false,west=tall,
[INFO] [default] Unknown block minecraft:cobblestone_wall east=none,north=tall,south
[INFO] [default] Unknown block minecraft:cobblestone_wall east=none,north=tall,south=none,up=true,waterlogged=false,west=tall,
[INFO] [default] Unknown block minecraft:cobblestone_wall east=tall,north=tall,south
[INFO] [default] Unknown block minecraft:cobblestone_wall east=tall,north=tall,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:diorite_wall east=none,north=low,south=low,
[INFO] [default] Unknown block minecraft:diorite_wall east=none,north=low,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:diorite_wall east=none,north=none,south=non
[INFO] [default] Unknown block minecraft:diorite_wall east=none,north=none,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:mossy_stone_brick_wall east=low,north=none,
[INFO] [default] Unknown block minecraft:mossy_stone_brick_wall east=low,north=none,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:mossy_stone_brick_wall east=none,north=none
[INFO] [default] Unknown block minecraft:mossy_stone_brick_wall east=none,north=none,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:mossy_stone_brick_wall east=none,north=none,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:mossy_stone_brick_wall east=none,north=none,south=none,up=true,waterlogged=false,west=tall,
[INFO] [default] Unknown block minecraft:mossy_stone_brick_wall east=tall,north=none
[INFO] [default] Unknown block minecraft:mossy_stone_brick_wall east=tall,north=none,south=none,up=false,waterlogged=false,west=tall,
[INFO] [default] Unknown block minecraft:mossy_stone_brick_wall east=tall,north=none,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:sandstone_wall east=low,north=low,south=non
[INFO] [default] Unknown block minecraft:sandstone_wall east=low,north=low,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:sandstone_wall east=low,north=none,south=lo
[INFO] [default] Unknown block minecraft:sandstone_wall east=low,north=none,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:sandstone_wall east=low,north=none,south=no
[INFO] [default] Unknown block minecraft:sandstone_wall east=low,north=none,south=none,up=false,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:sandstone_wall east=low,north=none,south=none,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=low,south=lo
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=low,south=low,up=false,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=low,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=low,south=no
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=low,south=none,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=none,south=l
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=none,south=low,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=none,south=n
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=none,south=none,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:sandstone_wall east=none,north=none,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=low,north=low,south=n
[INFO] [default] Unknown block minecraft:stone_brick_wall east=low,north=low,south=none,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=low,north=none,south=
[INFO] [default] Unknown block minecraft:stone_brick_wall east=low,north=none,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=low,north=none,south=none,up=false,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=low,south=
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=low,south=low,up=false,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=low,south=low,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=low,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=low,south=none,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=low,south=tall,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=none,south
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=none,south=low,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=none,south=low,up=true,waterlogged=false,west=none,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=none,south=none,up=true,waterlogged=false,west=low,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=none,south=none,up=true,waterlogged=false,west=tall,
[INFO] [default] Unknown block minecraft:stone_brick_wall east=none,north=none,south=tall,up=true,waterlogged=false,west=none,
[WARNING] [default] Unknown biome with id 51
[WARNING] [default] Unknown biome with id 52
[WARNING] [default] Unknown biome with id 60
[WARNING] [default] Unknown biome with id 62
[WARNING] [default] Unknown biome with id 66
[WARNING] [default] Unknown biome with id 68
[WARNING] [default] Unknown biome with id 70
[WARNING] [default] Unknown biome with id 76
[WARNING] [default] Unknown biome with id 78
[WARNING] [default] Unknown biome with id 82
[WARNING] [default] Unknown biome with id 83
[WARNING] [default] Unknown biome with id 84
[WARNING] [default] Unknown biome with id 85
[WARNING] [default] Unknown biome with id 90
[WARNING] [default] Unknown biome with id 92
[WARNING] [default] Unknown biome with id 93
[WARNING] [default] Unknown biome with id 94
[WARNING] [default] Unknown biome with id 98
[WARNING] [default] Unknown biome with id 100
[WARNING] [default] Unknown biome with id 106
[WARNING] [default] Unknown biome with id 108
[WARNING] [default] Unknown biome with id 109
[WARNING] [default] Unknown biome with id 110
[WARNING] [default] Unknown biome with id 112
[WARNING] [default] Unknown biome with id 113
[WARNING] [default] Unknown biome with id 114
[WARNING] [default] Unknown biome with id 116
[WARNING] [default] Unknown biome with id 122
[WARNING] [default] Unknown biome with id 123
[WARNING] [default] Unknown biome with id 124
[WARNING] [default] Unknown biome with id 126
[WARNING] [default] Unknown biome with id 128
[WARNING] [default] Unknown biome with id 137
[WARNING] [default] Unknown biome with id 138
[WARNING] [default] Unknown biome with id 139
[WARNING] [default] Unknown biome with id 141
[WARNING] [default] Unknown biome with id 143
[WARNING] [default] Unknown biome with id 145
[WARNING] [default] Unknown biome with id 147
[WARNING] [default] Unknown biome with id 148
[WARNING] [default] Unknown biome with id 154
[WARNING] [default] Unknown biome with id 159
[WARNING] [default] Unknown biome with id 173
[WARNING] [default] Unknown biome with id 176
[WARNING] [default] Unknown biome with id 177
[WARNING] [default] Unknown biome with id 179
[WARNING] [default] Unknown biome with id 180
[WARNING] [default] Unknown biome with id 181
[WARNING] [default] Unknown biome with id 182
[WARNING] [default] Unknown biome with id 183
[WARNING] [default] Unknown biome with id 185
[WARNING] [default] Unknown biome with id 187
[WARNING] [default] Unknown biome with id 188
[WARNING] [default] Unknown biome with id 189
[WARNING] [default] Unknown biome with id 190
[WARNING] [default] Unknown biome with id 191
[WARNING] [default] Unknown biome with id 192
[WARNING] [default] Unknown biome with id 193
[WARNING] [default] Unknown biome with id 195
[WARNING] [default] Unknown biome with id 198
[WARNING] [default] Unknown biome with id 200
[WARNING] [default] Unknown biome with id 201
[WARNING] [default] Unknown biome with id 202
[WARNING] [default] Unknown biome with id 203
[WARNING] [default] Unknown biome with id 204
[WARNING] [default] Unknown biome with id 207
[WARNING] [default] Unknown biome with id 208
[WARNING] [default] Unknown biome with id 211
[WARNING] [default] Unknown biome with id 213
[WARNING] [default] Unknown biome with id 214
[WARNING] [default] Unknown biome with id 216
[WARNING] [default] Unknown biome with id 217
[WARNING] [default] Unknown biome with id 219
[WARNING] [default] Unknown biome with id 220
[WARNING] [default] Unknown biome with id 221
[WARNING] [default] Unknown biome with id 222
[WARNING] [default] Unknown biome with id 223
[WARNING] [default] Unknown biome with id 224
[WARNING] [default] Unknown biome with id 225
[WARNING] [default] Unknown biome with id 226
[WARNING] [default] Unknown biome with id 227
[WARNING] [default] Unknown biome with id 229
[WARNING] [default] Unknown biome with id 233
[WARNING] [default] Unknown biome with id 234
[WARNING] [default] Unknown biome with id 235
[WARNING] [default] Unknown biome with id 236
[WARNING] [default] Unknown biome with id 237
[WARNING] [default] Unknown biome with id 238
[WARNING] [default] Unknown biome with id 241
[WARNING] [default] Unknown biome with id 242
[WARNING] [default] Unknown biome with id 243
[WARNING] [default] Unknown biome with id 245
[WARNING] [default] Unknown biome with id 249
[WARNING] [default] Unknown biome with id 251
[WARNING] [default] Unknown biome with id 252
[WARNING] [default] Unknown biome with id 253
[WARNING] [default] Unknown biome with id 255
```

**Review by elamperti — APPROVED** [review]
Thanks for your work! Looks good :)

@m0r13 There's a small change in `src/mapcraftercore/mc/chunk.cpp` you may want to check

**Comment by elamperti** [comment]
@miclav Could you resolve the conflicts this branch has with `world113`?

**Comment by miclav** [comment]
I would love to, but those are png/binary files, they just new to be accepted directly, there's no merging to do.
I don't have write access to the repo to resolve the conflict.

**Comment by miclav** [comment]
@fredkilbourn I just pushed the changed to blockcrafter to generate the right files for 1.16.
But those blockstates files were already generated in the mapcrafter projects. You just need to to run blockcrafter to regenerate those if you use a custom texture pack, is that the case ?

**Comment by fredkilbourn** [comment]
@miclav I was building my own blocks using your blockcrafter repo, not using the distributed ones.  I'll pull your blockcrafter commit https://github.com/miclav/blockcrafter/commit/cc29627c06784c3dc46b2a258960990d14385a67 and retry, and mapcrafter https://github.com/miclav/mapcrafter/commit/af98b7d181309f1174458504ffa1e8a303d014bf.

**Comment by elamperti** [comment]
@miclav Perhaps you have an outdated `world113` branch? These files already exist in `world113` at least since we merged your PR for 1.15 (PR #348), and we get this conflicts because this branch and the current `world113` are diverging.

If it gets too complicated to merge/rebase those changes let me know and I'll try to fix them in a separate branch. Thanks again! :)

**Comment by fredkilbourn** [comment]
@elamperti The problem is these files are static generated files that are updated and override the previous versions for each minecraft release.  There's no alternate location for them or option to not replace them.  Without updating them mapcrafter will be unable to render blocks released in newer Minecraft versions.

@miclav After using the last updates you just made to your blockcrafter and mapcrafter branches everything is working perfectly with my custom block render.

**Comment by elamperti** [comment]
@fredkilbourn it's just a git issue :) I'm not asking him to remove the files (which I understand we need for this version), but git can't merge the branch as it is because it doesn't know how to solve the conflict (i.e. it can't tell automatically which PNG files to leave in the repository, because both branches have different files with the same name). I'll create a separate branch to fix it if Michael isn't able to do so. In any case, don't worry: the resulting code will have these files.

**Comment by fredkilbourn** [comment]
@elamperti My apologies!  Didn't know the details haha.

**Review by m0r13 — APPROVED** [review]

**Review by m0r13 — APPROVED** [review]

**Comment by elamperti** [comment]
Conflicts solved (4909fbb), merging :slightly_smiling_face:

**Comment by elamperti** [comment]
Thanks once again for your work @miclav! :rocket:

**Pull request merged**
