### PR TITLE
Initial attempt at 1.12 textures

### PR DESCRIPTION
**Pull request by lucymhdavies**
With thanks to @seraphimkimiko

From 1.12:
http://minecraft.gamepedia.com/1.12#Blocks

Done:
- Concrete
- Concrete Powder

Not Done yet:
- Glazed Terracotta
- Beds

----

From 1.11

Not Done:
- Observer
- Shulker Box

----

Potentially there are other changes needed, but this is at least somewhere to start from, if others wish to test.

### CODE REVIEW

**Comment by lucymhdavies** [comment]
e.g. beds:

```
2017-06-08 20:37:27 [WARNING] [default] Unable to load block texture 'bed_feet_end.png'.
2017-06-08 20:37:27 [WARNING] [default] Unable to load block texture 'bed_feet_side.png'.
2017-06-08 20:37:27 [WARNING] [default] Unable to load block texture 'bed_feet_top.png'.
2017-06-08 20:37:27 [WARNING] [default] Unable to load block texture 'bed_head_end.png'.
2017-06-08 20:37:27 [WARNING] [default] Unable to load block texture 'bed_head_side.png'.
2017-06-08 20:37:27 [WARNING] [default] Unable to load block texture 'bed_head_top.png'.
2017-06-08 20:37:27 [WARNING] [default] Unable to load some block textures.
```

**Comment by lucymhdavies** [comment]
We have Glazed Teracotta kinda working on a different branch
https://github.com/lucymhdavies/mapcrafter/tree/beta
Though it's only got one rotation.

Not looked into beds yet, nor observers, so they're missing still.

Shulker blocks aren't playing nice.

Screenshots of blocks so far:
screen shot 2017-06-08 at 22 19 55
screen shot 2017-06-08 at 22 19 45

and a Minecraft screenshot for comparison
screen shot 2017-06-08 at 22 24 32

**Comment by Bjarno** [comment]
I think we worked almost simultaneously (I did not see this pull request when I forked the repository), so I think we did some "double work". But I have implemented support for all orientations. However, I do see that you have beds working (and I don't, yet).

https://github.com/mapcrafter/mapcrafter/pull/256


I'll try to cherry-pick your bed code to incorporate them with my changes, if you don't mind?

**Comment by lucymhdavies** [comment]
Nice work :)

You are however mistaken. We do not have beds working :(

**Comment by Bjarno** [comment]
Yeah, I saw that (but a bit too late). I was looking at the last screenshot, but that is in-game. My bad. I edited my post, but it did not update the initial notification.

**Comment by lucymhdavies** [comment]
Closing in favour of more complete https://github.com/mapcrafter/mapcrafter/pull/256

**Comment by m0r13** [comment]
The PR of @Bjarno is merged by now. There will be a new version soon. @lucymhdavies thanks for your efforts too!

**Pull request closed without merging**
